spring.application.name=daw-espam-libros-jwt

# Base de datos
spring.datasource.url=jdbc:mariadb://servidor.local.com:3306/daw_biblioteca_db
spring.datasource.username=daw_espam
spring.datasource.password=Cl4v3.2026!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

# Servidor
server.port = 8080

# JWT
security.jwt.secret-key=
security.jwt.expiration-ms=86400000