spring.application.name=daw-espam-libros-jwt

# Base de datos
spring.datasource.url=jdbc:mysql://grupofmo.com:3306/daw_biblioteca_db
spring.datasource.username=usuario_daw
spring.datasource.password=Cl4v3.2026!
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Servidor
server.port = 8080

# JWT
security.jwt.secret-key=ClaveSuperSeguraJWT2026HS256ABCD
security.jwt.expiration-ms=86400000